require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "Gemfile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - app/admin/*
    - spec/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
